services:
  hi-events-frontend:
    build:
      context: ./../../frontend
      dockerfile: Dockerfile.ssr
    container_name: hi-events-frontend
    ports:
      - "8126:5678"
    env_file:
      - .env
    restart: unless-stopped
